[build-system]
requires = ["setuptools>=61.0", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "valuascript-compiler"
dynamic = ["version"]

[tool.setuptools_scm]
'SETUPTOOLS_SCM_PRETEND_VERSION_FOR_VALUASCRIPT_COMPILER'.
fallback_version = "0.0.1" 